name: check python code

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11","3.12"]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
           python-version: ${{ matrix.python-version }}
           
      - name: install linter flake
        run: pip install flake8

      - name: scan code for syntax
        run: flake8 app.py
           
          
  
